// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package ai_metathings_component_service_digit_video_recorder

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Record struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StartAt              *timestamp.Timestamp `protobuf:"bytes,2,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	EndAt                *timestamp.Timestamp `protobuf:"bytes,3,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Record) Reset()         { *m = Record{} }
func (m *Record) String() string { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()    {}
func (*Record) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *Record) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Record.Unmarshal(m, b)
}
func (m *Record) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Record.Marshal(b, m, deterministic)
}
func (m *Record) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Record.Merge(m, src)
}
func (m *Record) XXX_Size() int {
	return xxx_messageInfo_Record.Size(m)
}
func (m *Record) XXX_DiscardUnknown() {
	xxx_messageInfo_Record.DiscardUnknown(m)
}

var xxx_messageInfo_Record proto.InternalMessageInfo

func (m *Record) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Record) GetStartAt() *timestamp.Timestamp {
	if m != nil {
		return m.StartAt
	}
	return nil
}

func (m *Record) GetEndAt() *timestamp.Timestamp {
	if m != nil {
		return m.EndAt
	}
	return nil
}

type OpRecord struct {
	Id                   *wrappers.StringValue `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StartAt              *timestamp.Timestamp  `protobuf:"bytes,2,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	EndAt                *timestamp.Timestamp  `protobuf:"bytes,3,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *OpRecord) Reset()         { *m = OpRecord{} }
func (m *OpRecord) String() string { return proto.CompactTextString(m) }
func (*OpRecord) ProtoMessage()    {}
func (*OpRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *OpRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpRecord.Unmarshal(m, b)
}
func (m *OpRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpRecord.Marshal(b, m, deterministic)
}
func (m *OpRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpRecord.Merge(m, src)
}
func (m *OpRecord) XXX_Size() int {
	return xxx_messageInfo_OpRecord.Size(m)
}
func (m *OpRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_OpRecord.DiscardUnknown(m)
}

var xxx_messageInfo_OpRecord proto.InternalMessageInfo

func (m *OpRecord) GetId() *wrappers.StringValue {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *OpRecord) GetStartAt() *timestamp.Timestamp {
	if m != nil {
		return m.StartAt
	}
	return nil
}

func (m *OpRecord) GetEndAt() *timestamp.Timestamp {
	if m != nil {
		return m.EndAt
	}
	return nil
}

type GetRecordRequest struct {
	Record               *OpRecord `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetRecordRequest) Reset()         { *m = GetRecordRequest{} }
func (m *GetRecordRequest) String() string { return proto.CompactTextString(m) }
func (*GetRecordRequest) ProtoMessage()    {}
func (*GetRecordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *GetRecordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRecordRequest.Unmarshal(m, b)
}
func (m *GetRecordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRecordRequest.Marshal(b, m, deterministic)
}
func (m *GetRecordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRecordRequest.Merge(m, src)
}
func (m *GetRecordRequest) XXX_Size() int {
	return xxx_messageInfo_GetRecordRequest.Size(m)
}
func (m *GetRecordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRecordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRecordRequest proto.InternalMessageInfo

func (m *GetRecordRequest) GetRecord() *OpRecord {
	if m != nil {
		return m.Record
	}
	return nil
}

type GetRecordResponse struct {
	Record               *Record  `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRecordResponse) Reset()         { *m = GetRecordResponse{} }
func (m *GetRecordResponse) String() string { return proto.CompactTextString(m) }
func (*GetRecordResponse) ProtoMessage()    {}
func (*GetRecordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}

func (m *GetRecordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRecordResponse.Unmarshal(m, b)
}
func (m *GetRecordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRecordResponse.Marshal(b, m, deterministic)
}
func (m *GetRecordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRecordResponse.Merge(m, src)
}
func (m *GetRecordResponse) XXX_Size() int {
	return xxx_messageInfo_GetRecordResponse.Size(m)
}
func (m *GetRecordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRecordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRecordResponse proto.InternalMessageInfo

func (m *GetRecordResponse) GetRecord() *Record {
	if m != nil {
		return m.Record
	}
	return nil
}

type ListRecordsRequest struct {
	// Types that are valid to be assigned to Filter:
	//	*ListRecordsRequest_Range
	Filter               isListRecordsRequest_Filter `protobuf_oneof:"filter"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *ListRecordsRequest) Reset()         { *m = ListRecordsRequest{} }
func (m *ListRecordsRequest) String() string { return proto.CompactTextString(m) }
func (*ListRecordsRequest) ProtoMessage()    {}
func (*ListRecordsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{4}
}

func (m *ListRecordsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRecordsRequest.Unmarshal(m, b)
}
func (m *ListRecordsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRecordsRequest.Marshal(b, m, deterministic)
}
func (m *ListRecordsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRecordsRequest.Merge(m, src)
}
func (m *ListRecordsRequest) XXX_Size() int {
	return xxx_messageInfo_ListRecordsRequest.Size(m)
}
func (m *ListRecordsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRecordsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRecordsRequest proto.InternalMessageInfo

type isListRecordsRequest_Filter interface {
	isListRecordsRequest_Filter()
}

type ListRecordsRequest_Range struct {
	Range *ListRecordsRequestRange_ `protobuf:"bytes,1,opt,name=range,proto3,oneof"`
}

func (*ListRecordsRequest_Range) isListRecordsRequest_Filter() {}

func (m *ListRecordsRequest) GetFilter() isListRecordsRequest_Filter {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *ListRecordsRequest) GetRange() *ListRecordsRequestRange_ {
	if x, ok := m.GetFilter().(*ListRecordsRequest_Range); ok {
		return x.Range
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ListRecordsRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ListRecordsRequest_Range)(nil),
	}
}

type ListRecordsRequestRange_ struct {
	StartAt              *timestamp.Timestamp `protobuf:"bytes,1,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	EndAt                *timestamp.Timestamp `protobuf:"bytes,2,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ListRecordsRequestRange_) Reset()         { *m = ListRecordsRequestRange_{} }
func (m *ListRecordsRequestRange_) String() string { return proto.CompactTextString(m) }
func (*ListRecordsRequestRange_) ProtoMessage()    {}
func (*ListRecordsRequestRange_) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{4, 0}
}

func (m *ListRecordsRequestRange_) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRecordsRequestRange_.Unmarshal(m, b)
}
func (m *ListRecordsRequestRange_) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRecordsRequestRange_.Marshal(b, m, deterministic)
}
func (m *ListRecordsRequestRange_) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRecordsRequestRange_.Merge(m, src)
}
func (m *ListRecordsRequestRange_) XXX_Size() int {
	return xxx_messageInfo_ListRecordsRequestRange_.Size(m)
}
func (m *ListRecordsRequestRange_) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRecordsRequestRange_.DiscardUnknown(m)
}

var xxx_messageInfo_ListRecordsRequestRange_ proto.InternalMessageInfo

func (m *ListRecordsRequestRange_) GetStartAt() *timestamp.Timestamp {
	if m != nil {
		return m.StartAt
	}
	return nil
}

func (m *ListRecordsRequestRange_) GetEndAt() *timestamp.Timestamp {
	if m != nil {
		return m.EndAt
	}
	return nil
}

type ListRecordsResponse struct {
	Records              []*Record `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListRecordsResponse) Reset()         { *m = ListRecordsResponse{} }
func (m *ListRecordsResponse) String() string { return proto.CompactTextString(m) }
func (*ListRecordsResponse) ProtoMessage()    {}
func (*ListRecordsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{5}
}

func (m *ListRecordsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRecordsResponse.Unmarshal(m, b)
}
func (m *ListRecordsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRecordsResponse.Marshal(b, m, deterministic)
}
func (m *ListRecordsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRecordsResponse.Merge(m, src)
}
func (m *ListRecordsResponse) XXX_Size() int {
	return xxx_messageInfo_ListRecordsResponse.Size(m)
}
func (m *ListRecordsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRecordsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListRecordsResponse proto.InternalMessageInfo

func (m *ListRecordsResponse) GetRecords() []*Record {
	if m != nil {
		return m.Records
	}
	return nil
}

func init() {
	proto.RegisterType((*Record)(nil), "ai.metathings.component.service.digit_video_recorder.Record")
	proto.RegisterType((*OpRecord)(nil), "ai.metathings.component.service.digit_video_recorder.OpRecord")
	proto.RegisterType((*GetRecordRequest)(nil), "ai.metathings.component.service.digit_video_recorder.GetRecordRequest")
	proto.RegisterType((*GetRecordResponse)(nil), "ai.metathings.component.service.digit_video_recorder.GetRecordResponse")
	proto.RegisterType((*ListRecordsRequest)(nil), "ai.metathings.component.service.digit_video_recorder.ListRecordsRequest")
	proto.RegisterType((*ListRecordsRequestRange_)(nil), "ai.metathings.component.service.digit_video_recorder.ListRecordsRequest.range_")
	proto.RegisterType((*ListRecordsResponse)(nil), "ai.metathings.component.service.digit_video_recorder.ListRecordsResponse")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 462 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x93, 0x41, 0x6b, 0x13, 0x41,
	0x14, 0xc7, 0x33, 0x89, 0xd9, 0xa6, 0x2f, 0x28, 0x3a, 0x82, 0xc4, 0x55, 0x34, 0xec, 0xa9, 0x07,
	0x99, 0x62, 0x54, 0x50, 0x10, 0xa1, 0xa2, 0xb6, 0x82, 0x50, 0xd8, 0x94, 0x5c, 0xc3, 0x36, 0xfb,
	0xba, 0x8e, 0x64, 0x77, 0xc6, 0x99, 0x97, 0x8a, 0x57, 0x3f, 0x88, 0x07, 0xf1, 0x43, 0xf9, 0x5d,
	0xbc, 0xc8, 0xee, 0xcc, 0x96, 0x76, 0x83, 0x28, 0xdb, 0xd0, 0xeb, 0xcc, 0x7b, 0xbf, 0xff, 0xff,
	0xbd, 0xff, 0x0c, 0x5c, 0xb7, 0x68, 0x4e, 0xe5, 0x02, 0x85, 0x36, 0x8a, 0x14, 0x7f, 0x9a, 0x48,
	0x91, 0x23, 0x25, 0xf4, 0x51, 0x16, 0x99, 0x15, 0x0b, 0x95, 0x6b, 0x55, 0x60, 0x41, 0xa2, 0x2e,
	0x4b, 0x65, 0x26, 0x69, 0x7e, 0x2a, 0x53, 0x54, 0x73, 0x83, 0x0b, 0x65, 0x52, 0x34, 0xe1, 0xbd,
	0x4c, 0xa9, 0x6c, 0x89, 0xbb, 0x15, 0xe3, 0x78, 0x75, 0xb2, 0x8b, 0xb9, 0xa6, 0xaf, 0x0e, 0x19,
	0x3e, 0x68, 0x5e, 0x7e, 0x31, 0x89, 0xd6, 0x68, 0xac, 0xbf, 0x7f, 0xd8, 0xbc, 0x27, 0x99, 0xa3,
	0xa5, 0x24, 0xd7, 0xae, 0x20, 0xfa, 0xc6, 0x20, 0x88, 0x2b, 0x29, 0x7e, 0x03, 0xba, 0x32, 0x1d,
	0xb1, 0x31, 0xdb, 0xd9, 0x8e, 0xbb, 0x32, 0xe5, 0xcf, 0x60, 0x60, 0x29, 0x31, 0x34, 0x4f, 0x68,
	0xd4, 0x1d, 0xb3, 0x9d, 0xe1, 0x24, 0x14, 0x0e, 0x27, 0x6a, 0x9c, 0x38, 0xaa, 0x71, 0xf1, 0x56,
	0x55, 0xbb, 0x47, 0xfc, 0x31, 0x04, 0x58, 0xa4, 0x65, 0x53, 0xef, 0x9f, 0x4d, 0x7d, 0x2c, 0xd2,
	0x3d, 0x8a, 0x7e, 0x30, 0x18, 0x1c, 0x6a, 0x6f, 0xe3, 0xd1, 0x99, 0x8d, 0xe1, 0xe4, 0xfe, 0x5a,
	0xef, 0x94, 0x8c, 0x2c, 0xb2, 0x59, 0xb2, 0x5c, 0xe1, 0x15, 0x9b, 0xfc, 0x04, 0x37, 0xf7, 0x91,
	0x9c, 0xc9, 0x18, 0x3f, 0xaf, 0xd0, 0x12, 0x9f, 0x41, 0xe0, 0x72, 0xf2, 0x7e, 0x5f, 0x89, 0x36,
	0x11, 0x8b, 0x7a, 0xf6, 0xd8, 0xd3, 0x22, 0x09, 0xb7, 0xce, 0x69, 0x59, 0xad, 0x0a, 0x8b, 0xfc,
	0xa8, 0x21, 0xf6, 0xb2, 0x9d, 0x58, 0x43, 0xea, 0x37, 0x03, 0xfe, 0x41, 0x5a, 0x2f, 0x66, 0xeb,
	0xc9, 0x32, 0xe8, 0x9b, 0xa4, 0xc8, 0xd0, 0x6b, 0x1d, 0xb6, 0xd3, 0x5a, 0x07, 0x8b, 0x8a, 0x3a,
	0x3f, 0xe8, 0xc4, 0x8e, 0x1f, 0x1a, 0x08, 0xdc, 0xd1, 0x85, 0x28, 0x59, 0x9b, 0x28, 0xbb, 0xff,
	0x19, 0xe5, 0xeb, 0x01, 0x04, 0x27, 0x72, 0x49, 0x68, 0xa2, 0x1c, 0x6e, 0x5f, 0xf0, 0xe8, 0x57,
	0x3d, 0x83, 0x2d, 0x37, 0x83, 0x1d, 0xb1, 0x71, 0xef, 0xd2, 0xbb, 0xae, 0x61, 0x93, 0x5f, 0x3d,
	0xb8, 0xfb, 0xa6, 0x2c, 0x9c, 0x95, 0x75, 0xb1, 0x2f, 0x9b, 0x3a, 0x04, 0x7f, 0x01, 0xfd, 0x69,
	0x39, 0x14, 0xbf, 0xb3, 0x36, 0xc2, 0xdb, 0xf2, 0xcf, 0x87, 0x7f, 0x39, 0x8f, 0x3a, 0xfc, 0x39,
	0x5c, 0x9b, 0x92, 0xd2, 0x2d, 0x3a, 0xbf, 0x33, 0xd8, 0x3e, 0x7b, 0x6b, 0xfc, 0x5d, 0xbb, 0x39,
	0x9b, 0x1f, 0x23, 0xdc, 0xbf, 0x34, 0xc7, 0x25, 0x11, 0x75, 0xf8, 0x4f, 0x06, 0xc3, 0x73, 0x19,
	0xf1, 0x83, 0x4d, 0x3d, 0xc5, 0xf0, 0xfd, 0x06, 0x48, 0xb5, 0xcd, 0xe3, 0xa0, 0xda, 0xec, 0x93,
	0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xcd, 0xe9, 0x43, 0xea, 0xf4, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DigitVideoRecorderServiceClient is the client API for DigitVideoRecorderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DigitVideoRecorderServiceClient interface {
	Start(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
	Stop(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
	GetRecord(ctx context.Context, in *GetRecordRequest, opts ...grpc.CallOption) (*GetRecordResponse, error)
	ListRecords(ctx context.Context, in *ListRecordsRequest, opts ...grpc.CallOption) (*ListRecordsResponse, error)
}

type digitVideoRecorderServiceClient struct {
	cc *grpc.ClientConn
}

func NewDigitVideoRecorderServiceClient(cc *grpc.ClientConn) DigitVideoRecorderServiceClient {
	return &digitVideoRecorderServiceClient{cc}
}

func (c *digitVideoRecorderServiceClient) Start(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/ai.metathings.component.service.digit_video_recorder.DigitVideoRecorderService/Start", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *digitVideoRecorderServiceClient) Stop(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/ai.metathings.component.service.digit_video_recorder.DigitVideoRecorderService/Stop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *digitVideoRecorderServiceClient) GetRecord(ctx context.Context, in *GetRecordRequest, opts ...grpc.CallOption) (*GetRecordResponse, error) {
	out := new(GetRecordResponse)
	err := c.cc.Invoke(ctx, "/ai.metathings.component.service.digit_video_recorder.DigitVideoRecorderService/GetRecord", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *digitVideoRecorderServiceClient) ListRecords(ctx context.Context, in *ListRecordsRequest, opts ...grpc.CallOption) (*ListRecordsResponse, error) {
	out := new(ListRecordsResponse)
	err := c.cc.Invoke(ctx, "/ai.metathings.component.service.digit_video_recorder.DigitVideoRecorderService/ListRecords", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DigitVideoRecorderServiceServer is the server API for DigitVideoRecorderService service.
type DigitVideoRecorderServiceServer interface {
	Start(context.Context, *empty.Empty) (*empty.Empty, error)
	Stop(context.Context, *empty.Empty) (*empty.Empty, error)
	GetRecord(context.Context, *GetRecordRequest) (*GetRecordResponse, error)
	ListRecords(context.Context, *ListRecordsRequest) (*ListRecordsResponse, error)
}

// UnimplementedDigitVideoRecorderServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDigitVideoRecorderServiceServer struct {
}

func (*UnimplementedDigitVideoRecorderServiceServer) Start(ctx context.Context, req *empty.Empty) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Start not implemented")
}
func (*UnimplementedDigitVideoRecorderServiceServer) Stop(ctx context.Context, req *empty.Empty) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stop not implemented")
}
func (*UnimplementedDigitVideoRecorderServiceServer) GetRecord(ctx context.Context, req *GetRecordRequest) (*GetRecordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRecord not implemented")
}
func (*UnimplementedDigitVideoRecorderServiceServer) ListRecords(ctx context.Context, req *ListRecordsRequest) (*ListRecordsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRecords not implemented")
}

func RegisterDigitVideoRecorderServiceServer(s *grpc.Server, srv DigitVideoRecorderServiceServer) {
	s.RegisterService(&_DigitVideoRecorderService_serviceDesc, srv)
}

func _DigitVideoRecorderService_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DigitVideoRecorderServiceServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ai.metathings.component.service.digit_video_recorder.DigitVideoRecorderService/Start",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DigitVideoRecorderServiceServer).Start(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DigitVideoRecorderService_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DigitVideoRecorderServiceServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ai.metathings.component.service.digit_video_recorder.DigitVideoRecorderService/Stop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DigitVideoRecorderServiceServer).Stop(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DigitVideoRecorderService_GetRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DigitVideoRecorderServiceServer).GetRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ai.metathings.component.service.digit_video_recorder.DigitVideoRecorderService/GetRecord",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DigitVideoRecorderServiceServer).GetRecord(ctx, req.(*GetRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DigitVideoRecorderService_ListRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DigitVideoRecorderServiceServer).ListRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ai.metathings.component.service.digit_video_recorder.DigitVideoRecorderService/ListRecords",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DigitVideoRecorderServiceServer).ListRecords(ctx, req.(*ListRecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DigitVideoRecorderService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ai.metathings.component.service.digit_video_recorder.DigitVideoRecorderService",
	HandlerType: (*DigitVideoRecorderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Start",
			Handler:    _DigitVideoRecorderService_Start_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _DigitVideoRecorderService_Stop_Handler,
		},
		{
			MethodName: "GetRecord",
			Handler:    _DigitVideoRecorderService_GetRecord_Handler,
		},
		{
			MethodName: "ListRecords",
			Handler:    _DigitVideoRecorderService_ListRecords_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
